### ISSUE TITLE
Create JSON-LD in responses

### ISSUE THREAD

**Issue by jdeck88** [localcontexts/localcontextshub#199]
Adding JSON-LD helps with machine interoperability.  Suggestion from @pbuttigieg to add schema.org tags in JSON-LD to help contextualize labels.   This should require some discussion here.  

In the context of the API request, an example JSON response is, e.g. https://localcontextshub.org/api/v1/projects/35449cb1-7ae9-410d-a6c0-1d2deb874e6b/?format=json
 
You to Pier Luigi Buttigieg (Direct Message) (May 30, 2024, 2:32 PM)
You are saying we should add JSON-ld to the JSON output?
 
Pier Luigi Buttigieg (Direct Message) (May 30, 2024, 2:34 PM)
Yes, with schema.org semantics - no one is going to understand some / most of those fields without custom coding we're helping LC develop the templates in ODIS: https://github.com/iodepo/odis-in/issues/11
I'm sure that can be used by the LC Hub and many other systems - there's nothing ODIS-specific about it

**Comment by arojas1** [comment]
Hi @jdeck88, yes this is on our radar for when the schema.org mappings are complete to include those fields within the project metadata that can be pulled or downloaded from the Hub based on what Notices/Labels are applied to the project. (I'll link this to our internal issue tracker for when we get to this step)
